name: Auto Workflow

on:
   schedule:
      - cron: "*/30 * * * *"
   workflow_dispatch:

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        
        - name: Auto Commit
          run: |
             echo " " >> README.md
             git config user.name "Yifei Zhou"
             git config user.email "yfzhou23@gmail.com"
             git add .
             git commit -m "Auto Workflow"
             git push
